### ISSUE TITLE
Using MongoDB Client gives a ClassCastException

### ISSUE THREAD

**Issue by marinusgeuze** [dazraf/vertx-hot#37]
Dear Dazraf,

I am using the vertx-mongo-client libary. During hot redeploy I get this error. Is there anyway to resolve this:

Best regards,
# Marinus

java.lang.ClassCastException: io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder cannot be cast to io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder
        at io.vertx.ext.mongo.impl.MongoClientImpl.lookupHolder(MongoClientImpl.java:515)
        at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:69)
        at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:64)
        at nl.metjekindnaarbuiten.Main.start(Main.java:65)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dazraf** [comment]
Hi Marinus,

Thank you for raising this! Will look into it around Thursday this week. I'm hoping to raise and finish a few issues (including this one) to make a release this coming weekend. 

Regards
Fuzz

**Comment by marinusgeuze** [comment]
Daar Fuzz,

Thanks a lot. Then I can start developing a vert.x application using hot
deploy and debugging capabilities. Tools which are necessary for a proper
developer experience.

Thanks again.

Best regards,
Marinus

**Comment by marinusgeuze** [comment]
Dear Fuzz,

Did you have time to look into this issue. I hope so.

Thanks in advance.

Best regards,
Marinus

**Comment by marinusgeuze** [comment]
Dear Fuzz,

Did you have time to look into this issue. I hope so.

Thanks in advance.

Best regards,
Marinus
